Brand.find_or_create_by(name: "シャネル")
Brand.find_or_create_by(name: "ナイキ")
Brand.find_or_create_by(name: "ルイヴィトン")
Brand.find_or_create_by(name: "シュプリーム")
Brand.find_or_create_by(name: "アディダス")
FirstCategory.find_or_create_by(name: "レディース")
FirstCategory.find_or_create_by(name: "メンズ")
FirstCategory.find_or_create_by(name: "ベビー・キッズ")
FirstCategory.find_or_create_by(name: "インテリア・住まい・小物")
FirstCategory.find_or_create_by(name: "本・音楽・ゲーム")
FirstCategory.find_or_create_by(name: "おもちゃ・ホビー・グッズ")
FirstCategory.find_or_create_by(name: "コスメ・香水・美容")
FirstCategory.find_or_create_by(name: "家電・スマホ・カメラ")
FirstCategory.find_or_create_by(name: "スポーツ・レジャー")
FirstCategory.find_or_create_by(name: "ハンドメイド")
FirstCategory.find_or_create_by(name: "チケット")
FirstCategory.find_or_create_by(name: "自動車・オートバイ")
FirstCategory.find_or_create_by(name: "その他")
SecondCategory.find_or_create_by(name: "トップス", first_category_id: "1")
SecondCategory.find_or_create_by(name: "ジャケット/アウター", first_category_id: "1")
SecondCategory.find_or_create_by(name: "パンツ", first_category_id: "1")
SecondCategory.find_or_create_by(name: "スカート", first_category_id: "1")
SecondCategory.find_or_create_by(name: "ワンピース", first_category_id: "1")
SecondCategory.find_or_create_by(name: "靴", first_category_id: "1")
SecondCategory.find_or_create_by(name: "ルームウェア/パジャマ", first_category_id: "1")
SecondCategory.find_or_create_by(name: "レッグウェア", first_category_id: "1")
Size.find_or_create_by(name: "XXS以下")
Size.find_or_create_by(name: "XS(SS)")
Size.find_or_create_by(name: "S")
Size.find_or_create_by(name: "M")
Size.find_or_create_by(name: "L")
Size.find_or_create_by(name: "XL(LL)")
Size.find_or_create_by(name: "2XL(3L)")
Size.find_or_create_by(name: "3XL(4L)")
Size.find_or_create_by(name: "4XL(5L)以上")
Size.find_or_create_by(name: "FREE SIZE")
ThirdCategory.find_or_create_by(name: "Tシャツ/カットソー", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "シャツ/ブラウス", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "ポロシャツ", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "キャミソール", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "タンクトップ", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "ニット/セーター", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "カーディガン", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "パーカー", second_category_id: "1")
