SecondCategory.find_or_create_by(name: "トップス", first_category_id: "1")
SecondCategory.find_or_create_by(name: "ジャケット/アウター", first_category_id: "1")
SecondCategory.find_or_create_by(name: "パンツ", first_category_id: "1")
SecondCategory.find_or_create_by(name: "スカート", first_category_id: "1")
SecondCategory.find_or_create_by(name: "ワンピース", first_category_id: "1")
SecondCategory.find_or_create_by(name: "靴", first_category_id: "1")
SecondCategory.find_or_create_by(name: "ルームウェア/パジャマ", first_category_id: "1")
SecondCategory.find_or_create_by(name: "レッグウェア", first_category_id: "1")
