ThirdCategory.find_or_create_by(name: "Tシャツ/カットソー", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "シャツ/ブラウス", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "ポロシャツ", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "キャミソール", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "タンクトップ", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "ニット/セーター", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "カーディガン", second_category_id: "1")
ThirdCategory.find_or_create_by(name: "パーカー", second_category_id: "1")
